### ISSUE TITLE
CI: Push interim versions of kong-operator to a public registry and garbage collect them

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#21]
The scope of this issue is to define a GitHub Actions workflow (possibly a part of the build-test-package-push one) which:
- builds the kong-operator image at the given revision
- pushes it to a docker registry (tagged by commit hash or something similar, maybe including branch name)

and manage the lifetime of such images (e.g. delete after 2 weeks or if more than X are present)

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
