### ISSUE TITLE
CI: Validate `olm/`

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#22]
Mimic the "catalog build" test defined [in the operator registry repo](https://github.com/operator-framework/community-operators/blob/master/.travis.yml) on our side.

One way to test would be by trying to build this image (thus mimicking the validation happening on their CI):
```dockerfile
FROM quay.io/operator-framework/upstream-registry-builder:v1.5.6 as builder
COPY olm manifests/kong
RUN ./bin/initializer -o ./bundles.db
```

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
