### ISSUE TITLE
Release: write a script and/or human checklist on releasing a new version to RHM

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#25]
Similar to #23, but the scope is to deliver the release to RHM as opposed to OperatorHub.
The version we deliver to RHM is different (Red Hat certified) than the OperatorHub one, so this issue depends on #24.

**Comment by mflendrich** [comment]
Blocked by #24 because #24 will invalidate the preexisting process.

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
