### ISSUE TITLE
CI: Test the "RH-certified" operator at HEAD

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#26]
Same as #20 but tests the (different) version of kong-operator that we deliver to RHM, as opposed to the one that we deliver to OperatorHub.

**Comment by mflendrich** [comment]
Blocked by #24 because there is nothing to test in `master` before we close #24.

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
