### ISSUE TITLE
cannot have two Kong CRs with equal names in different namespaces

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#33]
At kong-operator v0.3.0, applying two `Kong` resources - one in namespace `default` and then one in another namespace - causes the release of the latter to fail with the following error:

`{"level":"error","ts":1596404364.0087516,"logger":"helm.controller","msg":"Release failed","namespace":"potato","name":"example-kong","apiVersion":"charts.helm.k8s.io/v1alpha1","kind":"Kong","release":"example-kong","error":"failed to install release: rendered manifest     s contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: ClusterRole, namespace: , name: example-kong-kong","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:12     8\ngithub.com/operator-framework/operator-sdk/pkg/helm/controller.HelmOperatorReconciler.Reconcile\n\tsrc/github.com/operator-framework/operator-sdk/pkg/helm/controller/reconcile.go:196\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHand     ler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.     go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-201     91004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.0.0-     20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}  `

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
