### ISSUE TITLE
test OLM integration on CI

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#40]
Per instructions at https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md#1-get-a-kubernetes-cluster , in order to match the community operators guidelines, we need to test the _Testing Operator Deployment on Kubernetes_ and _Testing Operator Deployment on OpenShift_ paths. It seems reasonable to automate both on CI.

Currently our CI test runs the operator without OLM.

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
