### ISSUE TITLE
spike: OpenShift-certified Kong Operator

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#45]
The goal of this spike is to define steps necessary to ensure that the existing RH-certified (aka OpenShift-certified, see [docs](https://redhat-connect.gitbook.io/certified-operator-guide/)) Kong Operator, living under the `fork/certified` branch (reintegration of fork into mainline handled in #42):
- gets released in parallel with the non-certified variant, matching one another in functionality,
- is [offline-enabled](https://redhat-connect.gitbook.io/certified-operator-guide/appendix/offline-enabled-operators). It seems from past discussions that the current version (under `fork/certified` at the moment of writing) matches this criterion - if so, then the scope is to guarantee offline-enablement for future releases, possibly including tests in a simulated offline setup.
- is visible on the OperatorHub Console as a certified operator.

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
