### ISSUE TITLE
Old Version of Operator Causing Errors

### ISSUE THREAD

**Issue by mrhillsman** [Kong/kong-operator#46]
Hi,

We have an open bug https://bugzilla.redhat.com/show_bug.cgi?id=1882870 due to the 0.1.0 version of the operator still showing up in the OpenShift Operator Hub. While the version was archived unfortunately it still is visible and we actually need permission to remove it if it is no longer a valid version.

**Comment by hbagdi** [comment]
ping @rainest @mflendrich

**Comment by rainest** [comment]
@mrhillsman simply written permission, or something else from our end? You're fine to go ahead and remove it; shouldn't be any reason to continue using it or have it still listed as available.

**Comment by mrhillsman** [comment]
Thanks for the confirmation.

**Comment by brianwcook** [comment]
I am missing some specifics about what to do.  Have you deprecated an entire package name in favor of a new one?  Or deprecated a specific version of one package?

**Comment by rainest** [comment]
0.1.0 and variants (the RH Bugzilla ticket mentions v0.1.0-2 specifically) should be deprecated, I suppose? What works best on your end?

**Comment by mrhillsman** [comment]
@brianwcook

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
