### ISSUE TITLE
release Operator using Helm chart 1.11

### ISSUE THREAD

**Issue by mflendrich** [Kong/kong-operator#47]

**Comment by rainest** [comment]
Updated from 1.10 to 1.11; we created a new chart release since this was originally filed, and there shouldn't be any reason to not leapfrog. Minor issue there is that both chart releases have breaking changes, so we should make sure to link both sections of https://github.com/Kong/charts/blob/main/charts/kong/UPGRADE.md in the Operator changelog.

**Comment by mflendrich** [comment]
OperatorHub PR: https://github.com/operator-framework/community-operators/pull/2515
