### ISSUE TITLE
Migrate user documentation to docs.konghq.com

### ISSUE THREAD

**Issue by rainest** [Kong/kong-operator#55]
Split into an operator-specific issue from https://github.com/Kong/charts/issues/237#issuecomment-769295899

Not much content here yet because there are open questions about other parts of the operator documentation:

> <operator doc migration> is uncertain because implementation of service-apis will likely have substantial overlap with Kong Operator. Depending on the path forward for service-apis, the upcoming operator for Gateways is likely to have significant feature overlap with Kong Operator.

However, we do eventually want the operator user docs on the docs site instead of the repo.

**Comment by shaneutt** [comment]
This issue is being closed due to our recent [deprecation](https://github.com/Kong/kong-operator#deprecation-notice) of this repository. Having realized that Helm-based operators were too limiting for some of the things we wanted to do, we are now working on a [Golang-based Operator](https://github.com/kong/operator) to replace it and we encourage you to star and watch that repository to track our progress going forward. If you have questions or want to get in touch with us, please feel free to drop a message in the [#kong channel on Kubernetes Slack](https://kubernetes.slack.com/messages/kong).
