### ISSUE TITLE
conformance: `HTTPRouteHeaderMatching` test

### ISSUE THREAD

**Issue by mlavacca** [Kong/kong-operator#57]
## Problem Statement

KIC `ControlPlane` is already HTTP core conformant; the test `HTTPRouteHeaderMatching` is part of it. We need to run such a core test successfully. 

## Acceptance Criteria

- [ ] The core test `HTTPRouteHeaderMatching` is successfully run.

**Comment by pmalek** [comment]
This is only supported on `expressions` Kong Gateway router flavor in KIC (ref: https://github.com/Kong/kubernetes-ingress-controller/blob/d8c30ad0bdf84b11f9f60bd2b164d7d9398f60b0/test/conformance/gateway_conformance_test.go#L24-L27)

In order to support this we'll need to 
- change the default router flavor and set it via envs in `DataPlane` https://github.com/Kong/gateway-operator/blob/5d2fa24878762af9a00dae289a8191a5674fe4a2/internal/utils/dataplane/config.go#L15-L40
- or provide 2 conformance reports: for `expressions` and `traditional_compatible` (as [it's done in KIC](https://github.com/Kong/kubernetes-ingress-controller/blob/d8c30ad0bdf84b11f9f60bd2b164d7d9398f60b0/test/conformance/gateway_conformance_test.go#L60-L77))

**Comment by mlavacca** [comment]
Isn't expression the default router for KIC? In case we specify no router type, the expression one should be defaulted, or not?

**Comment by pmalek** [comment]
As per: https://docs.konghq.com/gateway/latest/reference/configuration/#router_flavor

The default is `traditional_compatible`. It's a default in **Kong Gateway** not in KIC. KIC only reads what's set on the Gateway via the Admin API: https://github.com/Kong/kubernetes-ingress-controller/blob/9b863786b5abc262987f3129b046a878511daec7/internal/manager/run.go#L107-L112.

We'd have to start setting this config value.
