### ISSUE TITLE
Official container image on bintray gated by permission

### ISSUE THREAD

**Issue by ojmhetar** [Kong/kong-operator#63]
Using the container image listed on Operator Hub: https://operatorhub.io/operator/kong

The image/version: kong-docker-kong-operator.bintray.io/kong-operator:v0.7.0

Fails to pull with: 
```
 Warning  Failed     17m (x4 over 21m)     kubelet            Failed to pull image "kong-docker-kong-operator.bintray.io/kong-operator:v0.7.0": rpc error: code = Unknown desc = failed to pull and unpack image "kong-docker-kong-operator.bintray.io/kong-operator:v0.7.0": failed to copy: httpReaderSeeker: failed open: unexpected status code https://kong-docker-kong-operator.bintray.io/v2/kong-operator/blobs/sha256:233b79455be5775c7e6d018c6bc2bc20f0d2be77d37bd2568f2532245dc98bb0: 403 Forbidden
  Normal   BackOff    6m35s (x52 over 21m)  kubelet            Back-off pulling image "kong-docker-kong-operator.bintray.io/kong-operator:v0.7.0"
  Warning  Failed     104s (x73 over 21m)   kubelet            Error: ImagePullBackOff
```

Could this be related to the deprecation message on bintray? https://bintray.com/kong/kong-operator/kong-operator

@rainest @mflendrich

**Comment by rainest** [comment]
Ah, forgot that there was the additional image for this.

I've migrated the existing images over to https://hub.docker.com/r/kong/kong-operator but haven't yet updated the Operator Hub content, since I'd like to do that alongside a release that includes updates to all the dependencies, which is pending completion of https://github.com/Kong/charts/pull/351

**Comment by rainest** [comment]
This repo and OperatorHub are now updated with the new repo location.
